#!/usr/bin/env bash
# Deploy Railway PDS to AWS (Lambda + S3 + CloudFront + custom domain)
#
# Prerequisites:
#   aws login
#   DNS access to zasya.online (Cloudflare) for CNAME records
#
# Usage:
#   ./scripts/deploy.sh
#   CUSTOM_DOMAIN=platform.zasya.online ./scripts/deploy.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REGION="${AWS_REGION:-ap-south-1}"
CERT_REGION="us-east-1"
STACK="${STACK_NAME:-railway-pds-chz}"
STATION="${STATION_CODE:-CHZ}"
CUSTOM_DOMAIN="${CUSTOM_DOMAIN:-platform.zasya.online}"

unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy 2>/dev/null || true

echo "==> Checking AWS credentials..."
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text --region "$REGION")
echo "    Account: $ACCOUNT_ID | Region: $REGION | Domain: $CUSTOM_DOMAIN"

ARTIFACT_BUCKET="railway-pds-artifacts-${ACCOUNT_ID}"

# ---------------------------------------------------------------------------
# Step 1: ACM certificate (us-east-1, required for CloudFront HTTPS)
# ---------------------------------------------------------------------------
echo ""
chmod +x "$ROOT/scripts/ensure-certificate.sh"
CERT_INFO=$(bash "$ROOT/scripts/ensure-certificate.sh" "$CUSTOM_DOMAIN")
CERT_ARN=$(echo "$CERT_INFO" | grep '^CertificateArn=' | cut -d= -f2)
CERT_STATUS=$(echo "$CERT_INFO" | grep '^Status=' | cut -d= -f2)

echo "    Certificate: $CERT_ARN"
echo "    Status: $CERT_STATUS"

if [ "$CERT_STATUS" = "PENDING_VALIDATION" ]; then
  echo ""
  if [ "${WAIT_FOR_CERT:-false}" = "true" ]; then
    echo "    Waiting for certificate validation (up to 30 min)..."
    aws acm wait certificate-validated \
      --certificate-arn "$CERT_ARN" \
      --region "$CERT_REGION"
  else
    echo "    Add the validation CNAME in Cloudflare, then re-run:"
    echo "    WAIT_FOR_CERT=true ./scripts/deploy.sh"
    exit 0
  fi
fi

# ---------------------------------------------------------------------------
# Step 2: Build & upload Lambda
# ---------------------------------------------------------------------------
echo ""
echo "==> Building Lambda..."
bash "$ROOT/scripts/build-lambda.sh"

if ! aws s3api head-bucket --bucket "$ARTIFACT_BUCKET" --region "$REGION" 2>/dev/null; then
  aws s3 mb "s3://${ARTIFACT_BUCKET}" --region "$REGION"
fi

aws s3 cp "$ROOT/dist/lambda.zip" "s3://${ARTIFACT_BUCKET}/lambda.zip" --region "$REGION"

# ---------------------------------------------------------------------------
# Step 3: Deploy main stack with CloudFront
# ---------------------------------------------------------------------------
echo ""
echo "==> Deploying CloudFormation stack: ${STACK}..."
aws cloudformation deploy \
  --template-file "$ROOT/infra/template.yaml" \
  --stack-name "$STACK" \
  --region "$REGION" \
  --capabilities CAPABILITY_IAM \
  --parameter-overrides \
    LambdaCodeBucket="$ARTIFACT_BUCKET" \
    LambdaCodeKey="lambda.zip" \
    StationCode="$STATION" \
    CustomDomainName="$CUSTOM_DOMAIN" \
    CertificateArn="$CERT_ARN" \
    AdminKey="${ADMIN_KEY:-chz-ops}" \
  --no-fail-on-empty-changeset

BUCKET=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" --output text)

CF_DOMAIN=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDomain'].OutputValue" --output text)

WEBSITE=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='WebsiteURL'].OutputValue" --output text)

REFRESH_FN=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='RefreshFunctionName'].OutputValue" --output text)

DIST_ID=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='DistributionId'].OutputValue" --output text 2>/dev/null || true)

# ---------------------------------------------------------------------------
# Step 4: Upload data + static site
# ---------------------------------------------------------------------------
echo ""
echo "==> Uploading station data..."
aws s3 cp "$ROOT/data/config.json" "s3://${BUCKET}/data/config.json" --region "$REGION"
aws s3 cp "$ROOT/data/trains.json" "s3://${BUCKET}/data/trains.json" --region "$REGION"

mkdir -p "$ROOT/dist/public"
cp -r "$ROOT/public/"* "$ROOT/dist/public/"

# Same-domain API via CloudFront /api/* — empty API_BASE uses relative paths
cat > "$ROOT/dist/public/config.js" <<EOF
// Auto-generated by deploy.sh
window.PDS_CONFIG = {
  API_BASE: '',
  REFRESH_MS: 30000
};
EOF

echo "==> Uploading static website..."
aws s3 sync "$ROOT/dist/public/" "s3://${BUCKET}/" \
  --exclude "data/*" \
  --delete \
  --region "$REGION"

aws s3 cp "$ROOT/data/config.json" "s3://${BUCKET}/data/config.json" --region "$REGION"
aws s3 cp "$ROOT/data/trains.json" "s3://${BUCKET}/data/trains.json" --region "$REGION"

echo "==> Invalidating CloudFront cache..."
if [ -n "$DIST_ID" ] && [ "$DIST_ID" != "None" ]; then
  aws cloudfront create-invalidation \
    --distribution-id "$DIST_ID" \
    --paths "/*" \
    --query 'Invalidation.Id' --output text > /dev/null
fi

echo "==> Triggering NTES refresh..."
aws lambda invoke \
  --function-name "$REFRESH_FN" \
  --region "$REGION" \
  --payload '{}' \
  /tmp/pds-refresh-out.json > /dev/null
cat /tmp/pds-refresh-out.json
echo ""

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "============================================"
echo "  Deployment complete!"
echo "============================================"
echo "  Custom domain  : https://${CUSTOM_DOMAIN}"
echo "  Admin panel    : https://${CUSTOM_DOMAIN}/admin.html"
echo "  CloudFront     : https://${CF_DOMAIN}"
echo "  S3 bucket      : ${BUCKET}"
echo "  Refresh        : every 1 minute"
echo "============================================"
echo ""
echo "==> FINAL STEP: Add this CNAME in Cloudflare DNS:"
echo ""
echo "    Type   : CNAME"
echo "    Name   : platform"
echo "    Target : ${CF_DOMAIN}"
echo "    Proxy  : OFF (DNS only / grey cloud) — required for ACM cert"
echo ""
echo "    After DNS propagates (5–30 min), open:"
echo "    https://${CUSTOM_DOMAIN}"
echo ""
